import axios from 'axios'

const baseURL = 'https://api.factures.tn/register'

const token =
  'eyJhbGciOiJSUzI1NiIsImtpZCI6IjU4NWI5MGI1OWM2YjM2ZDNjOTBkZjBlOTEwNDQ1M2U2MmY4ODdmNzciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZmFjdGFybmkiLCJhdWQiOiJmYWN0YXJuaSIsImF1dGhfdGltZSI6MTY2NDgxMjU3MCwidXNlcl9pZCI6InBtc09DaVEySWFWSENPVE5oZU1DUzl2SVJxODIiLCJzdWIiOiJwbXNPQ2lRMklhVkhDT1ROaGVNQ1M5dklScTgyIiwiaWF0IjoxNjY0ODEyNTcwLCJleHAiOjE2NjQ4MTYxNzAsImVtYWlsIjoiZGFya3BzaW5pZ2h0QGhvdG1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZGFya3BzaW5pZ2h0QGhvdG1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.SRn6IciNCKdJl1AA37jaAwK0KcasZPquOhtAAEhRpPceXrSR7dmrwY_08Q_jhd7Gny4erf4_yB10GC2HBTmSoPrqYg_GQOfwlBgqSnZ9nBLx-2b4jPgXhjonIgFURiUutIv9D7TJ2oN3wl3X5fT2aizxvIY4sGnYFtmz1U2qva0msIlaXgjq_veX3t5LzAryxrMlihqPD0GYwRTGHeh7JnAAcHO4-QGHUByEinU8OvVwkQL_0dhKhNmmb6iiqQ427wq0Dn0ghKcYDBhcDZF6XvYPYTQPdX1XWDilGMD6yucEOpQjXIMp-lH-ub5QJpMBTwmg6yL80BDXbXo59YVOug'

const config = { headers: { Authorization: `Bearer ${token}` } }

export const addUser = async (user) => {
  return await axios.post(`${baseURL}`, user, config)
}
